/**
 * @file ./out/scanner/file_io.h
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#ifndef _FILE_IO_H_
#define _FILE_IO_H_

#include "string_buffer.h"

/**
 * @brief File data structure type
 *
 */
typedef struct _file_t_ {
    string_t* name;
    FILE* fp;
    int line;
    int column;
    bool is_open;
    struct yy_buffer_state* buffer;
    struct _file_t_* next;
} file_t;

void open_file(const char* name, const char* ext);
//void close_file(void);
int get_char(void);
int get_line_no(void);
int get_col_no(void);
const char* get_file_name(void);
void update_numbers(void);
file_t* get_file_buffer(void);
void push_file_buffer(file_t*);
file_t* pop_file_buffer(void);
const char* get_base_file_name(string_t* str);

#endif /* _FILE_IO_H_ */
